### ISSUE TITLE
Allow dynamic recipients

### ISSUE THREAD

**Issue by brasilikum** [SchumacherFM/mailout#4]
I would like to send out the mail to the sender in cc. Therefore I would like to use form fields in the to, cc and bcc fields. Is it possible to add such a functionality or is this out of scope?

**Comment by SchumacherFM** [comment]
Yes of course it is possible and I thought on that during development because I got reminded to the beautiful http://www.scriptarchive.com/formmail.html Perl script which I used as the www was fresh ;-)

Because http://www.scriptarchive.com/formmail.html was so much abused for sending spam I decided not to add this feature.

At the moment I'm not really aware of a nice working securing mechanism which protects you from sending spam. The only idea I have to protect with the rate limit and a captcha.

What do you think?

**Comment by PythonLinks** [comment]
First thank you for all of the hard work. 

When a person registers, it would be nice to send them an email to please confirm. 
When I have an announcement, I would like to send it to everyone on some sub list. 
It would be great if I could do this.  It is not quite clear from your comments if this is possible or not. 


Maybe sending out to a list would require wome password, or only from the local host.  

Any chance of doing all of this.   Otherwise I have to install and configure a bunch of Python software. Sigh.  Your approach looks so much easier, it is all configured for me.

**Comment by SchumacherFM** [comment]
@PythonLinks Please use another tool as the purpose of this mailout plugin is to have minimal features. adding multiple emails via a FORM submit is dangerous. For your case youse mailchimp ;-)
